---
functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Пользователь должен иметь право редактировать свой код
  - Пользователь должен иметь возможность сдаться сопернику в игре
  - Пользователь должен иметь возможность видеть свой рейтинг
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Пользователь не должен иметь права редактировать код противника
  - Пользователь не должен иметь права редактировать код после завершения игры
  - Пользователь не должен иметь право редактировать не свой профиль
  
