---
functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве

implicit:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
